USE LIFEPRO;
GO

SELECT DISTINCT 
      pp.PAID_TO_DATE
    , ps.AMOUNT
    , PP.POLICY_NUMBER
	, SUBSTRING(CAST(PP.PAID_TO_DATE AS VARCHAR), 1,4) AS TAX_YEAR
    FROM PPOLC PP
	JOIN PPBEN_POLICY_BENEFITS					AS		pb		ON		pp.Policy_Number=pb.Policy_Number
	JOIN PPBEN_POLICY_BENEFITS_TYPES_BA_OR		AS		pbt		ON		pb.PBEN_ID=pbt.PBEN_ID
																			AND pb.BENEFIT_TYPE='BA'
	JOIN PPBEN_POLICY_BENEFITS					AS		be		ON		pp.Policy_Number=be.Policy_Number
	INNER JOIN PRELA_RELATIONSHIP_MASTER		AS		R		ON		SUBSTRING(R.IDENTIFYING_ALPHA,1,2) = pp.COMPANY_CODE 
																			AND SUBSTRING(R.IDENTIFYING_ALPHA,3,12)=pp.POLICY_NUMBER 
																			AND R.RELATE_CODE = 'IN'											
    join PSUSP_SUSPENSE_MASTER                  AS      ps      on      ps.SUSP_NUMBER = pp.POLICY_NUMBER
        
        WHERE N.DEATH_DATE = '' AND DECEASED_FLAG <> 'Y'
        AND ps.amount > 0.00
        AND ps.amount = pp.MODE_PREMIUM
		AND PP.CONTRACT_CODE = 'A'
