name: Run Batch Script

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  run-batch-script:
    runs-on: windows-latest # Run on a Windows machine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GitHub PAT (Personal Access Token)
        env:
          PAT: ${{ secrets.GITHUB_PAT }} # Store your PAT securely in GitHub Secrets
        run: |
          echo Setting up PAT for batch script...
          echo %PAT% # You can use it within your script or pass it dynamically to the script

      - name: Run Batch Script
        run: |
          # Assuming the batch script is in the root of your repository
          .\InsuranceService.bat
